### ISSUE TITLE
How to multipy a large tensor with smaller tensor

### ISSUE THREAD

**Issue by brappier** [liuliu/s4nnc#14]
I have 

```
a = Input()
b = Input()

c = a * b 
```

After building the model, i pass 
a -> NCHW((2,3,4,5)
b -> .N(1)

i get a shape mismatch error

Basically i want to build a model which takes a scaler and tensor as input and multiplies them and return a tensor.
How to do that?

**Comment by liuliu** [comment]
`a * b` is for matrix multiplication. I would try `a .* b` which is per element multiplication. If that still have mismatch, I would try to have b in the shape of `.NCHW(1, 1, 1, 1)`.

Also, if you just want to multiply a scalar, you should just simply do `scalar * a`, that should work both when a is a tensor, and a is a `Model.IO`.

**Comment by brappier** [comment]
That works thanks.
