### ISSUE TITLE
An easy interface to add custom accelerators / backends?

### ISSUE THREAD

**Issue by brappier** [liuliu/s4nnc#7]
There should be some easy framework, so that i can easily add my ops for custom accelerator / framework. 
I wanted to see if i can add easily port it to a proprietary chip aiming to outcompete M1 GPU. 

I really like TFs framework for adding custom backends but its too big.

**Comment by brappier** [comment]
If you can sigh NDAs and stuff, can share more details.

**Comment by liuliu** [comment]
Thanks for the offering! Sorry I didn't sign NDAs without knowing more details. (i.e. if NDA is about custom accelerators alone, we can discuss more in private channels).

**Comment by liuliu** [comment]
Also, you can check out tinygrad: https://github.com/geohot/tinygrad which supposedly should be easy to add custom backends.
