### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by brappier** [liuliu/s4nnc#8]
python bindings for s4nnc. 
Looks like it wont be hard to implement. 
a python wrapper on top of swift wrapper seems like a good idea.

**Comment by liuliu** [comment]
Would be a bit convoluted and since we have PyTorch, not sure the benefits.

It would be easy to use PythonKit and including Python execution though (i.e., building an app that support Python scripting capability while all autograd computation are done internally through s4nnc binding).
